In [2]:
import pandas as pd
import numpy as np

In [13]:
inv_raw = pd.read_csv('data/inventario_central_v2.csv')
trx_raw = pd.read_csv('data/transacciones_logistica_v2.csv')
fb_raw  = pd.read_csv('data/feedback_clientes_v2.csv')

inv = inv_raw.copy()
trx = trx_raw.copy()
fb  = fb_raw.copy()

In [23]:
inv.isnull().sum()

SKU_ID                  0
Categoria               0
Stock_Actual          100
Costo_Unitario_USD      0
Punto_Reorden           0
Lead_Time_Dias        403
Bodega_Origen           0
Ultima_Revision         0
dtype: int64

In [15]:
trx.isnull().sum()

Transaccion_ID            0
SKU_ID                    0
Fecha_Venta               0
Cantidad_Vendida          0
Precio_Venta_Final        0
Costo_Envio             834
Tiempo_Entrega_Real       0
Estado_Envio           1683
Ciudad_Destino            0
Canal_Venta               0
dtype: int64

In [16]:
fb.isnull().sum()

Feedback_ID                  0
Transaccion_ID               0
Rating_Producto              0
Rating_Logistica             0
Comentario_Texto           657
Recomienda_Marca          1119
Ticket_Soporte_Abierto       0
Edad_Cliente                 0
Satisfaccion_NPS             0
dtype: int64

In [17]:
inv.info()
inv.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   SKU_ID              2500 non-null   object
 1   Categoria           2500 non-null   object
 2   Stock_Actual        2400 non-null   float64
 3   Costo_Unitario_USD  2500 non-null   float64
 4   Punto_Reorden       2500 non-null   int64
 5   Lead_Time_Dias      2097 non-null   object
 6   Bodega_Origen       2500 non-null   object
 7   Ultima_Revision     2500 non-null   object
dtypes: float64(2), int64(1), object(5)
memory usage: 156.4+ KB

,SKU_ID,Categoria,Stock_Actual,Costo_Unitario_USD,Punto_Reorden,Lead_Time_Dias,Bodega_Origen,Ultima_Revision
0,PROD-1000,smart-phone,NaN,870.38,259,25-30 días,Norte,2025-11-17
1,PROD-1001,Accesorios,476.0,1397.26,169,25-30 días,Norte,2024-03-05
2,PROD-1002,Monitores,1209.0,611.62,214,5,Sur,2024-06-21
3,PROD-1003,smart-phone,1825.0,145.94,187,10,Sur,2025-01-07
4,PROD-1004,Smartphones,1713.0,77.78,105,5,Sur,2024-07-04

In [18]:
fb['Comentario_Texto'].value_counts(dropna=False)

Comentario_Texto
Excelente       677
Lento           668
NaN             657
Dañado          647
---             631
No volvería     624
Precio justo    596
Name: count, dtype: int64

In [19]:
inv.columns

Index(['SKU_ID', 'Categoria', 'Stock_Actual', 'Costo_Unitario_USD',
       'Punto_Reorden', 'Lead_Time_Dias', 'Bodega_Origen', 'Ultima_Revision'],
      dtype='object')

In [20]:
inv.dtypes

SKU_ID                 object
Categoria              object
Stock_Actual          float64
Costo_Unitario_USD    float64
Punto_Reorden           int64
Lead_Time_Dias         object
Bodega_Origen          object
Ultima_Revision        object
dtype: object

In [24]:
inv.duplicated().sum()
fb['Feedback_ID'].duplicated().sum()

np.int64(500)

In [25]:
fb[fb['Feedback_ID'].duplicated(keep=False)].sort_values('Feedback_ID').head(4)

,Feedback_ID,Transaccion_ID,Rating_Producto,Rating_Logistica,Comentario_Texto,Recomienda_Marca,Ticket_Soporte_Abierto,Edad_Cliente,Satisfaccion_NPS
2005,FB-10005,TRX-10058,1,5,---,SI,Sí,48,-9.4
4479,FB-10005,TRX-13264,4,2,No volvería,Maybe,0,73,1.1
2015,FB-10015,TRX-14240,5,2,No volvería,NO,0,33,-21.6
4115,FB-10015,TRX-18844,2,1,Lento,SI,1,41,-63.7

In [26]:
inv.head()

,SKU_ID,Categoria,Stock_Actual,Costo_Unitario_USD,Punto_Reorden,Lead_Time_Dias,Bodega_Origen,Ultima_Revision
0,PROD-1000,smart-phone,NaN,870.38,259,25-30 días,Norte,2025-11-17
1,PROD-1001,Accesorios,476.0,1397.26,169,25-30 días,Norte,2024-03-05
2,PROD-1002,Monitores,1209.0,611.62,214,5,Sur,2024-06-21
3,PROD-1003,smart-phone,1825.0,145.94,187,10,Sur,2025-01-07
4,PROD-1004,Smartphones,1713.0,77.78,105,5,Sur,2024-07-04

In [27]:
trx.head()

,Transaccion_ID,SKU_ID,Fecha_Venta,Cantidad_Vendida,Precio_Venta_Final,Costo_Envio,Tiempo_Entrega_Real,Estado_Envio,Ciudad_Destino,Canal_Venta
0,TRX-10000,PROD-3619,25/04/2025,-5,1752.48,NaN,999,Entregado,Bucaramanga,Físico
1,TRX-10001,PROD-1456,29/07/2025,12,686.88,67.16,29,Entregado,Ventas_Web,WhatsApp
2,TRX-10002,PROD-1102,31/05/2025,2,402.06,32.55,13,Perdido,MED,Físico
3,TRX-10003,PROD-2126,23/01/2026,4,665.98,62.64,12,Perdido,Medellín,Online
4,TRX-10004,PROD-2003,09/10/2025,5,1222.62,52.91,15,Entregado,BOG,App

In [28]:
fb.head()

,Feedback_ID,Transaccion_ID,Rating_Producto,Rating_Logistica,Comentario_Texto,Recomienda_Marca,Ticket_Soporte_Abierto,Edad_Cliente,Satisfaccion_NPS
0,FB-8000,TRX-17461,99,4,NaN,NaN,Sí,195,-17.5
1,FB-8001,TRX-17755,4,5,---,Maybe,Sí,59,-41.7
2,FB-8002,TRX-10534,3,4,No volvería,Maybe,0,84,-36.4
3,FB-8003,TRX-12569,2,3,---,NaN,Sí,20,7.4
4,FB-8004,TRX-19159,4,2,Dañado,SI,No,83,61.0

In [29]:
inv['Categoria'].unique()
inv['Bodega_Origen'].unique()

array(['Norte', 'Sur', 'ZONA_FRANCA', 'norte', 'BOD-EXT-99', 'Occidente'],
      dtype=object)

In [30]:
inv['Categoria'].unique()

array(['smart-phone', 'Accesorios', 'Monitores', 'Smartphones', '???',
       'Tablets', 'LAPTOP', 'Laptops'], dtype=object)

In [32]:
fb[['Rating_Producto','Edad_Cliente']].describe()

       Rating_Producto  Edad_Cliente
count      4500.000000   4500.000000
mean          3.635778     51.172889
std           7.942196     21.830784
min           1.000000     18.000000
25%           2.000000     34.000000
50%           3.000000     50.000000
75%           4.000000     67.000000
max          99.000000    195.000000

In [33]:
trx[['Cantidad_Vendida','Tiempo_Entrega_Real']].describe()

       Cantidad_Vendida  Tiempo_Entrega_Real
count      10000.000000         10000.000000
mean           7.413600            19.881900
std            4.205485            69.914879
min           -5.000000             1.000000
25%            4.000000             8.000000
50%            7.000000            15.000000
75%           11.000000            22.000000
max           14.000000           999.000000

In [34]:
inv[['Stock_Actual','Costo_Unitario_USD']].describe()

       Stock_Actual  Costo_Unitario_USD
count   2400.000000         2500.000000
mean     995.487083         1105.788816
std      597.689734        16989.836953
min      -50.000000            0.050000
25%      481.000000          403.652500
50%      987.000000          755.175000
75%     1523.250000         1125.292500
max     1998.000000       850000.000000

In [35]:
skus_transacciones = set(trx['SKU_ID'])
skus_inventario = set(inv['SKU_ID'])
fantasmas = skus_transacciones - skus_inventario

print(f"SKUs fantasma: {len(fantasmas)}")
print(f"Filas de ventas afectadas: {trx['SKU_ID'].isin(fantasmas).sum()} / {len(trx)}")

SKUs fantasma: 480
Filas de ventas afectadas: 1751 / 10000